#!/usr/bin/env bash

set -Eeuo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( cd ${SCRIPT_DIR}/.. ; pwd)

TOPIC="sensors/sensor-3542/control"

STATE=${1:-ON}

mosquitto_pub -h localhost -t $TOPIC -m $STATE
