#!/usr/bin/env bash


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( cd ${SCRIPT_DIR}/.. ; pwd)
LOG_FILE=/tmp/setup-confluent-iot-fleet-mgmt.log

echo "Start Setup" > $LOG_FILE

echo "##"
echo "## Create KSQL Tables and Streams"
echo "##"

$PROJECT_DIR/confluent-5.0.3/bin/ksql <<EOF &>> $LOG_FILE
  RUN SCRIPT '$PROJECT_DIR/yb-iot-fleet-management/iot-ksql-processor/setup_streams.ksql';
  exit
EOF
echo "" >> $LOG_FILE

echo "##"
echo "## Create Kafka Connect Connector - yugabyte-sink"
echo "##"
curl -s -X POST -H 'Content-Type: application/json' http://localhost:8083/connectors \
  -d '{
    "name" : "yugabyte-sink",
    "config" : {
      "confluent.license": "",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "key.converter.schemas.enable": false,
      "value.converter.schemas.enable": false,
      "offset.flush.interval.ms": "10000",
      "connector.class": "com.yb.connect.sink.YBSinkConnector",
      "yugabyte.cql.contact.points": "127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042",
      "yugabyte.cql.keyspace": "TrafficKeySpace",
      "yugabyte.cql.tablename": "Origin_Table",
      "topics": "iot-data-event"
    }
  }' &>> $LOG_FILE
echo "" >> $LOG_FILE

echo "##"
echo "## Create Kafka Connect Connector - yugabyte-sink-poi"
echo "##"

curl -s -X POST -H 'Content-Type: application/json' http://localhost:8083/connectors \
  -d '{
    "name" : "yugabyte-sink-poi",
    "config" : {
      "confluent.license": "",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "key.converter.schemas.enable": false,
      "value.converter.schemas.enable": false,
      "offset.flush.interval.ms": "10000",
      "connector.class": "com.yb.connect.sink.YBSinkConnector",
      "yugabyte.cql.contact.points": "127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042",
      "yugabyte.cql.keyspace": "TrafficKeySpace",
      "yugabyte.cql.tablename": "Poi_Traffic",
      "topics": "poi_traffic"
    }
  }' &>> $LOG_FILE
echo "" >> $LOG_FILE

echo "##"
echo "## Create Kafka Connect Connector - yugabyte-sink-total"
echo "##"

curl -s -X POST -H 'Content-Type: application/json' http://localhost:8083/connectors \
  -d '{
    "name" : "yugabyte-sink-total",
    "config" : {
      "confluent.license": "",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "key.converter.schemas.enable": false,
      "value.converter.schemas.enable": false,
      "offset.flush.interval.ms": "10000",
      "connector.class": "com.yb.connect.sink.YBSinkConnector",
      "yugabyte.cql.contact.points": "127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042",
      "yugabyte.cql.keyspace": "TrafficKeySpace",
      "yugabyte.cql.tablename": "Total_Traffic",
      "topics": "total_traffic"
    }
  }' &>> $LOG_FILE
echo "" >> $LOG_FILE

echo "##"
echo "## Create Kafka Connect Connector - yugabyte-sink-window"
echo "##"

curl -s -X POST -H 'Content-Type: application/json' http://localhost:8083/connectors \
  -d '{
    "name" : "yugabyte-sink-window",
    "config" : {
      "confluent.license": "",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "key.converter.schemas.enable": false,
      "value.converter.schemas.enable": false,
      "offset.flush.interval.ms": "10000",
      "connector.class": "com.yb.connect.sink.YBSinkConnector",
      "yugabyte.cql.contact.points": "127.0.0.1:9042,127.0.0.2:9042,127.0.0.3:9042",
      "yugabyte.cql.keyspace": "TrafficKeySpace",
      "yugabyte.cql.tablename": "Window_Traffic",
      "topics": "window_traffic"
    }
  }' &>> $LOG_FILE
echo "" >> $LOG_FILE

echo "Completed"
