#!/usr/bin/env bash

set -Eeuo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( cd ${SCRIPT_DIR}/.. ; pwd)

TOPIC="${1:-mqtt.temperature}"
SERVER="${2:-localhost:2181}"

confluent-5.0.3/bin/kafka-configs \
   --zookeeper $SERVER \
  --entity-type topics \
  --alter \
  --entity-name $TOPIC \
  --add-config retention.ms=1000

sleep 2

confluent-5.0.3/bin/kafka-configs \
  --zookeeper $SERVER \
  --entity-type topics \
  --alter \
  --entity-name $TOPIC \
  --add-config retention.ms=600000
